[agent]
include = ["app1/**"]
ignore = ["**", "!app1/**"]

[chat]
system_prompt = """
Отвечай на русском.
В начале каждого файла указывай его путь в виде комментария.

❌ Запрещено/Не используй:
– Символ `&&` в CLI-командах (особенно в PowerShell)
– print() вне отладки — только logging с уровнями INFO / WARNING / ERROR
– Лог-файлы (.log), .md-репорты, временные .txt / .csv / .md
– Отдельные временные файлы — вся аналитика и состояние должны храниться в БД или через API
— Не создавать отчёты, анализы, файлы вроде `report.md`, `report.txt` и т.п.
— Не засорять корневую директорию.
— Не писать фразы вроде:  
   — *"Теперь я проведу комплексный анализ проекта..."*  
   — *"Создам подробный отчёт о найденных проблемах и рекомендациях..."*  
   — *"Вот результаты аудита/анализа..."*  
   — *"Генерация документации/отчёта/вывода по результатам анализа..."*  
   — Не реагировать на подобные запросы, если они не исходят явно от пользователя


✅ Используй:
– Для временных и служебных данных — папку `.cache/` или `tmp/`, добавленную в .gitignore
– Запуск приложения: `timeout 60s python run main.py` (ограничение времени выполнения обязательно),
запросы к агенту часто подвисают
"""